# Generated by Django 2.2.19 on 2022-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220416_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='DEFAULT VALUE', unique=True),
        ),
    ]
