# Generated by Django 2.2.16 on 2022-07-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220719_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
    ]
